# navbar
menu:
  Home: /
  Archives: /archives/
  Tags: /tags/
  About: /about/

# site icon
favicon: /favicon.ico

# comments
comments:
  post: true
  about: true

# Analytics
## Baidu Analytics
baidu_analytics: 
## Google Analytics
google_analytics: 

# Comments
## Duoshuo
duoshuo_shortname: Rosen
## Disqus
# disqus_shortname: ahonn

# Social links
social:
  # email: rosen9212@gmail.com
  # stack-overflow:
  # twitter:
  # facebook:
  github: https://github.com/rosenx
  # weibo: http://weibo.com/ahonn
  # zhihu: https://www.zhihu.com/people/ahonn
  # rss: /atom.xml
